### ISSUE TITLE
how to add node after instllation completes?

### ISSUE THREAD

**Issue by Piping** [christianh814/ocp4-upi-helpernode#11]
HI,

Thanks for this awesome playbook & knowledge setup.

Currently I cannot find a way to add a node either automatically or manually after installation complete.

I updated the setup helper machine and HAproxy can display properly of all available workers.

But it appears that `oc get nodes` does not show new added node.

Any help? Thanks

**Comment by christianh814** [comment]
> HI,
> 
> Thanks for this awesome playbook & knowledge setup.
> 
> Currently I cannot find a way to add a node either automatically or manually after installation complete.
> 
> I updated the setup helper machine and HAproxy can display properly of all available workers.
> 
> But it appears that `oc get nodes` does not show new added node.
> 
> Any help? Thanks

You should check your CSRs; some of them might need manual approving.

```
oc get csr
```

You can approve all pending CSRs with the following command

```
oc get csr --no-headers | awk '{print $1}' | xargs oc adm certificate approve
```
```

**Comment by Piping** [comment]
Hi @christianh814 

are those nodes gonna appear and send csr automatically?
Because I cannot see new csr  nor `oc get nodes`

**Comment by christianh814** [comment]
@Piping 

It depends on how you added the node. What steps did you take to add a new node?

**Comment by Piping** [comment]
@christianh814 I use the PXE install to add more worker nodes. ( first add more entries in the vars.yaml and re-run playbook and then reload the services and last install).

**Comment by christianh814** [comment]
@Piping 

Ah okay, make sure that DNS is in place for that worker.

```
nslookup <hostname of new worker>
```

Also check the reverse

```
nslookup <ip of new worker>
```

It's possible the new entry didn't "take" so make sure it's in the zonefiles

```
helpernodecheck dns-workers
```

If it's in the output of `helpernodecheck` but not showing up with `nslookup`, you might have to update the serial numbers in the `/var/named/zonefile.db` and `/var/named/reverse.db` files and restart named

**Comment by Piping** [comment]
@christianh814 so I would not need a boostrap node again right?

All it matters after the initail configuration is that 
1) DNS `zonefile.db`/`reverse.db` are update to date (serial number update/ restart )
2) the  `ignition` configuration file for openshift stays the same?

Is that correct here?

**Comment by christianh814** [comment]
> @christianh814 so I would not need a boostrap node again right?
> 
> All it matters after the initail configuration is that
> 
>     1. DNS `zonefile.db`/`reverse.db` are update to date (serial number update/ restart )
> 
>     2. the  `ignition` configuration file for openshift stays the same?
> 
> 
> Is that correct here?

Correct, you won't need a bootstrap node again. You also don't need a new ignition file for the worker, you use the one you have.
