### ISSUE TITLE
run as non-root user

### ISSUE THREAD

**Issue by therevoman** [christianh814/ocp4-upi-helpernode#16]
It may be simply recommending the arguments `-b -K` after the `ansible-playbook` command when not running as root.

Is it expected these playbooks will be run as root?

**Comment by christianh814** [comment]
> It may be simply recommending the arguments `-b -K` after the `ansible-playbook` command when not running as root.
> 
> Is it expected these playbooks will be run as root?

The playbook needs to run as `root` or a user that has `sudo` privileges
