### ISSUE TITLE
Trouble pasting coreos options into boot menu

### ISSUE THREAD

**Issue by codeworks01** [christianh814/ocp4-upi-helpernode#23]
I am on Fedora 30 running Virtual Machine Manager 2.1.0 and I am unable to paste the boot info;

```
ip=$IPADDR::$DEFAULTGW:$NETMASK:$HOSTNAME:$INTERFACE:none:$DNS'
```

into the coreos boot menu. 

I have been trying to use the '--extra-args' flag to pass these parameters but no luck. 

```
args='ip=192.168.7.20::192.168.7.1:255.255.255.0:bootstrap:eth0:none:192.168.7.77 '
args='coreos.inst.install_dev=vda coreos.inst.image_url=http://192.168.7.77:8080/install/bios.raw.gz ' 
args='coreos.inst.ignition_url=http://192.168.7.77:8080/ignition/bootstrap-static.ign'

sudo virt-install --name=ocp4-bootstrap  \
--extra-args="${args}" \
--vcpus=4 --ram=8192 \
--disk path=/var/lib/libvirt/images/ocp4-bootstrap.qcow2,bus=virtio,size=120 \
--os-variant rhel8.0 --network network=openshift4,model=virtio \
--boot menu=on \
--cdrom /home/dischord01/Code/ocp4-workingdir/rhcos-4.1.0-x86_64-installer.iso
```

Is there any other way to pass these arguments or a way to copy and paste this into the bootmenu?

**Comment by christianh814** [comment]
This isn't an issue with this playbook nor `libvirt`; but with CoreOS. See the following for more information.

https://github.com/coreos/coreos-installer#testing-out-the-installer-running-in-the-initramfs-early-boot
