### ISSUE TITLE
RFE: Cleanup Playbook

### ISSUE THREAD

**Issue by christianh814** [christianh814/ocp4-upi-helpernode#29]
We should make a task/play that cleans up the environment

something like

```
ansible-playbook -e cleanup=true tasks/main.yaml
```

It should do the following...

* Remove all files/templates that were copied over
* Remove any packages installed
* It shouldn't run any other plays/tasks

**Comment by christianh814** [comment]
Looks like #35 does that...but should we consider an "uninstall" option? @therevoman @whowutwut ?

**Comment by whowutwut** [comment]
I think this is kind of nice for a "best practice" to undo the files for the helper.  But what about the  named and dhcp configs? Do you have a specific use case where we want to clean up? 

In the cluster i'm managing, I've gotten the deployment automation down to around 2 hours turn key with a fresh install..  So I reinstall the helper node each time with centOS, then clone clean and run it once to mange the bare metal cluster... if i need to undo it, i would just re-install  😄 

So I haven't yet found a need to clean up this helper files..  The helper also stays around to be the entry point to the openshift console, so i just leave it as is.

**Comment by christianh814** [comment]
I agree. Also the playbook is idempotent, so if you make a mistake; you can rerun the playbook with the updates.

I'm going to close this...if the issue comes up; then I will revisit it.

**Comment by christianh814** [comment]
Closed by #35
