### ISSUE TITLE
nmcli command return network name with spaces on centos

### ISSUE THREAD

**Issue by fctoibm** [christianh814/ocp4-upi-helpernode#30]
I updated to following code to help me with error

  - name: Get network interface name
    shell: "nmcli -t -f NAME c show --active"
    register: networkinterfacename

  - name: Setting network interface name as a fact
    set_fact:
      networkifacename: "{{ networkinterfacename.stdout }}"

  - name: Setting DNS server ip on network interface "{{ networkifacename }}" to 127.0.0.1
    command: "nmcli con mod '{{ networkifacename }}'  ipv4.dns 127.0.0.1"

  - name: Setting DNS search path on network interface "{{ networkifacename }}" to "{{ dns.clusterid }}.{{ dns.domain }}"
    command: "nmcli con mod '{{ networkifacename }}'  ipv4.dns-search {{ dns.clusterid }}.{{ dns.domain }}"

on my system the  is the name of con "System ens32"

**Comment by christianh814** [comment]
You need to put the name of the INTERFACE in the `vars.yaml` file...not the NetworkManager name. In your example, you'd put `"ens32"` 

Here's a snip (example)

```
helper:
  name: "helper"
  ipaddr: "192.168.7.77"
  networkifacename: "ens32"
```

I already take "space in networkmanager name" into account.
