### ISSUE TITLE
Can't stand up the master node: connection refused when getting config

### ISSUE THREAD

**Issue by whowutwut** [christianh814/ocp4-upi-helpernode#32]
This may not be the right place to ask this question, but giving it a shot... 

I'm using this playbook to attempt to stand up OCP4 and hitting a wall the last few days trying to stand up the masters/control plane.. 

The bootstrap node comes up fine, I can ssh as the core user... and journalctl shows waiting for the etcd cluster to start... HAproxy shows bootstrap node as green.   so i think my ssh and pullsecret are good... 

When I boot the master, i see it get the coreos and master.ign, and it installs to disk, then reboots.. on reboot, it's trying to get the `/config/master` from api-int and gets connection refused over and over... 

```
[ 1194.842680] ignition[842]: GET https://api-int.pok.stglabs.ibm.com:22623/config/master: attempt #240
[ 1194.853263] ignition[842]: GET error: Get https://api-int.pok.stglabs.ibm.com:22623/config/master: dial tcp: lookup api-int.pok.stglabs.ibm.com on [::1]:53: read udp [::1]:37135->[::1]:53: read: connection refused
```

I haven't made any changes to the playbook so the haproxy.config should be as the playbook would create.... only adding in the vars.yaml entries for my environment...  turned off firewall on the helper just to see if that improved anything, it didn't. 

`nslookup` of `api-int` gives back the helper IP address, and ping of api-int from bootstrap also gives back the helper IP address.  I turned on the haproxy-traffic logs on the helper node, I don't see any request coming into it from the master IP, only from the bootstrap node.  

I'm guessing that the master should be going to the bootstrap to get it's config. Is there any tips on how to debug on the bootstrap to see any incoming requests... ?

Thanks

**Comment by whowutwut** [comment]
It seems like the TCP traffic doesn't ever hit the helper node HAProxy IP address, seems to get reset.  Is there any way to add debug to the console on the master?  I tried adding `systemd.log_level=debug systemd.journald.max_level_console=debug` to the PXE append line for the master option, but I didn't seem to see any additional output. 

What I'm wondering if whether the gateway or nameserver IP is correctly sent to the master so it's resolving the `api-int` host correctly.  

Also, there's no possibilty of ipv6 coming into play here right?  Throwing out some wild guesses...

**Comment by christianh814** [comment]
Are you sure that the master is pulling the right ignition file? Also, you need to keep in mind, that the certificate for the bootstrap is only good for 24 hours....so make sure you start fresh each time (if you're debugging over a course of a few days).

Where are you installing it? Are you sure there's no firewallrules in your network preventing things?

**Comment by whowutwut** [comment]
Yea, I realized that 24 hour certificate with a different error msg at the end of last week 😄  so have been re-deploying almost daily, or multiple times a day... 

I just swapped the bootstrap server and master0 server this morning and bootstrap came up OK on that server... httpd logs when bootstrap depoyed:
```
172.29.0.184 - - [26/Sep/2019:09:31:50 -0400] "HEAD /install/bios.raw.gz HTTP/1.1" 200 - "-" "curl/7.61.1"
172.29.0.184 - - [26/Sep/2019:09:31:50 -0400] "GET /ignition/bootstrap.ign HTTP/1.1" 200 276723 "-" "curl/7.61.1"
172.29.0.184 - - [26/Sep/2019:09:31:50 -0400] "GET /install/bios.raw.gz HTTP/1.1" 200 719954527 "-" "curl/7.61.1"
```

once that's up and waiting for etcd cluster.. i kick off master and see it pull this: 
```
172.29.0.185 - - [26/Sep/2019:09:58:54 -0400] "HEAD /install/bios.raw.gz HTTP/1.1" 200 - "-" "curl/7.61.1"
172.29.0.185 - - [26/Sep/2019:09:58:54 -0400] "GET /ignition/master.ign HTTP/1.1" 200 1824 "-" "curl/7.61.1"
172.29.0.185 - - [26/Sep/2019:09:58:54 -0400] "GET /install/bios.raw.gz HTTP/1.1" 200 719954527 "-" "curl/7.61.1"
```

same issue "connection refused"... 

I'm installing on x86_64 nodes (older servers from 2012-2013) in the same server frame but taking a subset of servers from a larger cluster...  I am debating to separate out these 10 nodes to their own subnet... to get rid of some interference possibility  on the same subnet. 

From the helper and bootstrap node, I'm able to curl with insecure: `curl https://172.29.0.184:22623/config/master --insecure`  and that works fine...  I see it hit the  HAProxy, but no logs from the master. 

When I modified the master.ign to put an IP address instead of `api-int.domain` it complain `x509: cannot validate certificate for 172.29.0.183 because it doesn't contain any IP SANs` so couldn't validate if the master0 node is correctly resolving the right IP...  but tcpdump does seem to show it attempt to communicate with the haproxy IP. 

I did turn off the firewall on the helper..    the switch is local to the cluster, so it doesn't look like it's routing out further...   but I do see lots of TCP error when looking at `tcpdump` between the helper/bootstrap/master0... but all the master0 to helper communication get RESET immediately after the SYN packet.  ☹️  

So is there anything similar in CoreOS to enable ssh like anaconda where we can ssh to it during install and debug? But maybe at this point, it's booting CoreOS and trying to get config... not installing.

**Comment by whowutwut** [comment]
OK.. I stood up another helper, bootstrap, master0, master1 node in a smaller subnet, "172.30.2.0/24"...   

This is kind of interesting.... 

1. bootstrap comes up first time, i cannot ssh as core@bootstrap , decided to reinstall it... 
2. When it comes back... it's fine, I can ssh core@bootstrap... 

3. Bring up master0, I actually get to the login prompt!  But cannot ssh with core user, permission denied..
```
[root@helper tools]# ssh core@master0
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
[root@helper tools]#
```

I don't see any hits to the machine-config-server on the HAProxy 
![image](https://user-images.githubusercontent.com/10049070/65721869-ef7aa380-e078-11e9-915d-154c54fada5f.png)


4. Decided to reinstall, maybe same issue with bootstrap,...  on reinstall, comes back with the connection refused msg.. 
```
ignition[838]: GET error: Get https://api-int.ocp4-2.pok.stglabs.ibm.com:22623/config/master: dial tcp: lookup api-int.ocp4-2.pok.stglabs.ibm.com on [::1]:53: read udp [::1]:54398->[::1]:53: read: connection refused
```

5. Kick off master1 install...  it comes up with the boot prompt too.... but cannot ssh as core user... 
```
[root@helper tools]# ssh core@master1
Warning: Permanently added 'master1,172.30.2.22' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
[root@helper tools]#
```

I have a feeling if i reinstall it, it will also fail with connection refused...  

There's no way to get into CoreOS without the ssh keys right?

**Comment by whowutwut** [comment]
Just for completeness incase someone else hits this...  I'm not completely out of the woods yet as master0 is not able to turn Green in Haproxy, but I was able to at least get master to pull the machine-config and get to a prompt where I can `ssh core@master0`.... 

I think I was hitting issues with multiple DHCP... similar to https://github.com/coreos/bugs/issues/212  and decided to try to create Static IPs from the the quick start guide + filetranspiler.  

This got me around the `connection refused` problem but still missing domain search and nameserver attributes... but at least I'm able to get master0 up, but Kubelet is failing to start.  Will debug further.

**Comment by christianh814** [comment]
It might be related to this https://github.com/christianh814/ocp4-upi-helpernode/issues/33

**Comment by whowutwut** [comment]
I'm going to try and pull the nightly builds, I will also update based on #33.  I do see that when I'm providing static IPs through PXE, and the fakeroot, the search and DNS servers do not get into `/etc/resolv.conf`.. I have to go into the node and run `nmcli` commands to get masters to ping to the internet.

**Comment by codeworks01** [comment]
@whowutwut What was the final solution? I am having the same problem where the bootstrap comes up but the master gets the connection refused.

**Comment by whowutwut** [comment]
@codeworks01 For that problem, 2 posts above 

> I think I was hitting issues with multiple DHCP... similar to coreos/bugs#212 and decided to try to create Static IPs from the the quick start guide + filetranspiler.

I got past the connection refused by setting static IPs (using filetranspiler) on the master[0-2] nodes, instead of relying on DHCP, for some reason the x86 servers I'm using have issues with that.  So the IP address is getting set but the route gets hosed I think, so it's unable to route out correctly.

**Comment by codeworks01** [comment]
@whowutwut Thanks for the feedback, I got it to install, I found that I was not waiting long enough for the cluster to setup, I checked `journalctl` on the bootstrap node and saw that the cluster was installing, it just took some time for haproxy to register it.  I

**Comment by varunyn** [comment]
I am having the same error and not able to resolve it, is there a solution posted?

**Comment by whowutwut** [comment]
For myself.. ..  what fixed it for me is 2 comments above (https://github.com/christianh814/ocp4-upi-helpernode/issues/32#issuecomment-554683253) where I used `filetranspiler` to configure static IPs for the master nodes .. you have to create a fakeroot directory,  `master0/etc/sysconfig/network-scripts/ifcfg-en0` for example, then run it through `filetranspiler` to create a modified ignition file, then serve those files out. 

I saw some connection refused still for maybe 30-40 attempts while the coreOS node is configuring...  but if it's happening forever, then something else is wrong.
