### ISSUE TITLE
has no attribute 'name' during "Write out dhcp file"

### ISSUE THREAD

**Issue by rayashworth** [christianh814/ocp4-upi-helpernode#4]
[root@OCP4HelperNode ocp4-upi-helpernode]# ansible-playbook -vvvv -e @vars.yaml tasks/main.yml
ansible-playbook 2.7.10
  config file = /root/ocp4-upi-helpernode/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /root/ocp4-upi-helpernode/ansible.cfg as config file
setting up inventory plugins
/root/ocp4-upi-helpernode/inventory did not meet host_list requirements, check plugin documentation if this is unexpected
/root/ocp4-upi-helpernode/inventory did not meet script requirements, check plugin documentation if this is unexpected
Set default localhost to localhost
Parsed /root/ocp4-upi-helpernode/inventory inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: main.yml ***********************************************************************************************************
1 plays in tasks/main.yml
Read vars_file '../vars/main.yml'
Read vars_file '../vars/main.yml'
Read vars_file '../vars/main.yml'

PLAY [all] *******************************************************************************************************************
Read vars_file '../vars/main.yml'

TASK [Gathering Facts] *******************************************************************************************************
task path: /root/ocp4-upi-helpernode/tasks/main.yml:4
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1564676657.13-14509371742263 `" && echo ansible-tmp-1564676657.13-14509371742263="` echo /root/.ansible/tmp/ansible-tmp-1564676657.13-14509371742263 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<localhost> PUT /root/.ansible/tmp/ansible-local-14605XPjyco/tmpOxx6lv TO /root/.ansible/tmp/ansible-tmp-1564676657.13-14509371742263/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1564676657.13-14509371742263/ /root/.ansible/tmp/ansible-tmp-1564676657.13-14509371742263/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1564676657.13-14509371742263/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1564676657.13-14509371742263/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers
Read vars_file '../vars/main.yml'

TASK [Install needed packages] ***********************************************************************************************
task path: /root/ocp4-upi-helpernode/tasks/main.yml:9
Running yum as the backend for the yum action plugin
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1564676658.29-259646673103743 `" && echo ansible-tmp-1564676658.29-259646673103743="` echo /root/.ansible/tmp/ansible-tmp-1564676658.29-259646673103743 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/packaging/os/yum.py
<localhost> PUT /root/.ansible/tmp/ansible-local-14605XPjyco/tmpiO14sp TO /root/.ansible/tmp/ansible-tmp-1564676658.29-259646673103743/AnsiballZ_yum.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1564676658.29-259646673103743/ /root/.ansible/tmp/ansible-tmp-1564676658.29-259646673103743/AnsiballZ_yum.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1564676658.29-259646673103743/AnsiballZ_yum.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1564676658.29-259646673103743/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "allow_downgrade": false, 
            "autoremove": false, 
            "bugfix": false, 
            "conf_file": null, 
            "disable_excludes": null, 
            "disable_gpg_check": false, 
            "disable_plugin": [], 
            "disablerepo": [], 
            "download_only": false, 
            "enable_plugin": [], 
            "enablerepo": [], 
            "exclude": [], 
            "install_repoquery": true, 
            "installroot": "/", 
            "list": null, 
            "name": [
                "bind", 
                "bind-utils", 
                "haproxy", 
                "httpd", 
                "vim", 
                "bash-completion", 
                "libselinux-python", 
                "podman"
            ], 
            "releasever": null, 
            "security": false, 
            "skip_broken": false, 
            "state": "present", 
            "update_cache": false, 
            "update_only": false, 
            "use_backend": "auto", 
            "validate_certs": true
        }
    }, 
    "msg": "", 
    "rc": 0, 
    "results": [
        "32:bind-9.9.4-74.el7_6.1.x86_64 providing bind is already installed", 
        "32:bind-utils-9.9.4-74.el7_6.1.x86_64 providing bind-utils is already installed", 
        "haproxy-1.5.18-8.el7.x86_64 providing haproxy is already installed", 
        "httpd-2.4.6-89.el7_6.x86_64 providing httpd is already installed", 
        "2:vim-enhanced-7.4.160-6.el7_6.x86_64 providing vim is already installed", 
        "1:bash-completion-2.1-6.el7.noarch providing bash-completion is already installed", 
        "libselinux-python-2.5-14.1.el7.x86_64 providing libselinux-python is already installed", 
        "podman-1.3.2-1.git14fdcd0.el7.x86_64 providing podman is already installed"
    ]
}
Read vars_file '../vars/main.yml'

TASK [Install packages for DHCP/PXE install] *********************************************************************************
task path: /root/ocp4-upi-helpernode/tasks/main.yml:22
Running yum as the backend for the yum action plugin
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1564676659.74-239887889366478 `" && echo ansible-tmp-1564676659.74-239887889366478="` echo /root/.ansible/tmp/ansible-tmp-1564676659.74-239887889366478 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/packaging/os/yum.py
<localhost> PUT /root/.ansible/tmp/ansible-local-14605XPjyco/tmpQQ3bJ9 TO /root/.ansible/tmp/ansible-tmp-1564676659.74-239887889366478/AnsiballZ_yum.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1564676659.74-239887889366478/ /root/.ansible/tmp/ansible-tmp-1564676659.74-239887889366478/AnsiballZ_yum.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1564676659.74-239887889366478/AnsiballZ_yum.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1564676659.74-239887889366478/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "allow_downgrade": false, 
            "autoremove": false, 
            "bugfix": false, 
            "conf_file": null, 
            "disable_excludes": null, 
            "disable_gpg_check": false, 
            "disable_plugin": [], 
            "disablerepo": [], 
            "download_only": false, 
            "enable_plugin": [], 
            "enablerepo": [], 
            "exclude": [], 
            "install_repoquery": true, 
            "installroot": "/", 
            "list": null, 
            "name": [
                "dhcp", 
                "syslinux", 
                "tftp-server"
            ], 
            "releasever": null, 
            "security": false, 
            "skip_broken": false, 
            "state": "present", 
            "update_cache": false, 
            "update_only": false, 
            "use_backend": "auto", 
            "validate_certs": true
        }
    }, 
    "msg": "", 
    "rc": 0, 
    "results": [
        "12:dhcp-4.2.5-68.el7_5.1.x86_64 providing dhcp is already installed", 
        "syslinux-4.05-15.el7.x86_64 providing syslinux is already installed", 
        "tftp-server-5.2-22.el7.x86_64 providing tftp-server is already installed"
    ]
}
Read vars_file '../vars/main.yml'

TASK [Write out dhcp file] ***************************************************************************************************
task path: /root/ocp4-upi-helpernode/tasks/main.yml:31
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1564676660.36-121333902685348 `" && echo ansible-tmp-1564676660.36-121333902685348="` echo /root/.ansible/tmp/ansible-tmp-1564676660.36-121333902685348 `" ) && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1564676660.36-121333902685348/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "msg": "AnsibleUndefinedVariable: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'name'"
}
	to retry, use: --limit @/root/ocp4-upi-helpernode/tasks/main.retry

PLAY RECAP *******************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1   

[root@OCP4HelperNode ocp4-upi-helpernode]#

**Comment by rayashworth** [comment]
Running on RHEL 7.6

**Comment by christianh814** [comment]
@rayashworth This SHOULD be fixed by f3c3f71

Do the following

* `yum -y update` to get to RHEL 7.7 and `reboot`
* If using dhcp, make sure your [vars.yaml](https://github.com/christianh814/ocp4-upi-helpernode/blob/master/vars.yaml) is correct (and nothing is missing)
* Do a `git pull` to get the updated playbook 

Once you do that try again.

**Comment by christianh814** [comment]
Closing as I cannot recreate issue.
