### ISSUE TITLE
RFE: Include needed binaries/artificats for installation

### ISSUE THREAD

**Issue by christianh814** [christianh814/ocp4-upi-helpernode#42]
Include the artifacts/binaries need for installation in a directory. Have the `vars/main.yaml` use `file:///` instead of `https://` for the `get_file` module.

Pros:

* Saves from having to download each component, speeding up install
* Can be a precursor to creating a "disconnected helper"
* We can Test on specific versions of this playbook + OS + OCP version

Cons:

* Effectively ties the version of OCP to this playbook. making it somewhat less flexable
* Makes the repo bigger, therefore making "git clone" a bit heavy
* Although the helpernode isn't directly supported by RH, the cluster it installs is. "hosting" the binaries on here effectively makes the OCP cluster not supported either

**Comment by vchintal** [comment]
Cons makes it more reasonable not have binaries included in the repo. Most repos don't and folks can wait for the downloads to finish when doing it for the very first time. 

If you ask me, this should be closed ;) !

**Comment by whowutwut** [comment]
I would agree with @vchintal and prefer not checking binaries into the repo. I have a local node serving the files via http to keep version control.

**Comment by christianh814** [comment]
I agree with all points made here. Going to close this. Thank you all for the input!
