### ISSUE TITLE
Subnet in nameserver based on helpernode instead of dhcp pool

### ISSUE THREAD

**Issue by MaartenKreuger** [christianh814/ocp4-upi-helpernode#45]
The reverse name resolution fails when the helper node is in a different part of the subnet as the openshift nodes when using a class B subnet. This causes the nodes to stay named localhost, failing the install. 

Fix: In ocp4-upi-helpernode/templates/named.conf.j2  change:
zone "{{ helper.ipaddr.split('.')[2] }}.{{ helper.ipaddr.split('.')[1] }}.{{ helper.ipaddr.split('.')[0] }}.in-addr.arpa" IN {
into:
zone "{{ dhcp.poolstart.split('.')[2] }}.{{ dhcp.poolstart.split('.')[1] }}.{{ dhcp.poolstart.split('.')[0] }}.in-addr.arpa" IN {

**Comment by christianh814** [comment]
Closing as this repo has moved https://github.com/RedHatOfficial/ocp4-helpernode/issues
