### ISSUE TITLE
/usr/local/bin/helpernodecheck file not present

### ISSUE THREAD

**Issue by abhiniveshjain** [christianh814/ocp4-upi-helpernode#5]
/usr/local/bin/helpernodecheck file is not present hence it errors out.
similarly below file is not available
/usr/local/bin/checker.sh

**Comment by christianh814** [comment]
It's there for me

```
# /usr/local/bin/helpernodecheck
Usage:
helpernodecheck {dns-masters|dns-workers|dns-etcd|install-info|haproxy|services}
```

Make sure the playbook finishes completely and try again

**Comment by christianh814** [comment]
Can't reproduce /close
